input {
  file {
    path => "/data/opensearch/**/*"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }

  beats {
    port => 5044
  }

  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [message] =~ /^\s*$/ {
    drop { }
  }
}

output {
  opensearch {
    hosts => ["http://opensearch-node1:9200"]
    index => "logstash-%{+YYYY.MM.dd}"
  }
}
