# Master
spark.master                                    spark://spark-master:7077

# Event logging (History Server)
spark.eventLog.enabled                          true
spark.eventLog.dir                              /opt/spark/events
spark.history.fs.logDirectory                   /opt/spark/events

# Mémoire configurée pour une VM de 8Go
spark.executor.memory                           4g
spark.driver.memory                             2g
spark.executor.cores                            4

# SeaweedFS via S3
spark.hadoop.fs.s3a.endpoint                    http://seaweedfs-filer:8333
spark.hadoop.fs.s3a.access.key                  admin
spark.hadoop.fs.s3a.secret.key                  adminpass
spark.hadoop.fs.s3a.path.style.access           true
spark.hadoop.fs.s3a.impl                        org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.connection.ssl.enabled      false

# Hive Metastore
spark.sql.catalogImplementation                 hive
spark.hadoop.hive.metastore.uris                thrift://hive-metastore:9083
spark.sql.warehouse.dir                         s3a://warehouse/

# OpenSearch — connecteur permettant d'écrire directement depuis Spark
spark.opensearch.nodes                          opensearch
spark.opensearch.port                           9200
spark.opensearch.nodes.wan.only                 true
spark.opensearch.net.ssl                        false
